#!/usr/bin/python
# coding: utf-8


CHANNELS = {
            "type1":[
                {
                    "id":279,
                    "name":u"我是歌手",
                    "i":1
                },
                {
                    "id":281,
                    "name":u"中国好歌曲",
                    "i":1
                },
                {
                    "id":199,
                    "name":u"热歌",
                    "i":1
                },
                {
                    "id":126,
                    "name":u"新歌",
                    "i":1
                },
                {
                    "id":118,
                    "name":u"华语",
                    "i":1
                },
                {
                    "id":120,
                    "name":u"欧美",
                    "i":1
                },
                {
                    "id":119,
                    "name":u"粤语",
                    "i":1
                },
                {
                    "id":150,
                    "name":u"韩语",
                    "i":1
                },
                {
                    "id":268,
                    "name":u"佛教音乐",
                    "i":1
                },
                {
                    "id":269,
                    "name":u"健身频道",
                    "i":1
                },
                {
                    "id":270,
                    "name":u"KTV必点歌",
                    "i":1
                },
                {
                    "id":280,
                    "name":u"我是歌手控",
                    "i":1
                },
                {
                    "id":271,
                    "name":u"广场舞",
                    "i":1
                },
                {
                    "id":272,
                    "name":u"闽南语",
                    "i":1
                },
                {
                    "id":273,
                    "name":u"神曲",
                    "i":1
                },
                {
                    "id":274,
                    "name":u"轻松舒缓",
                    "i":1
                },
                {
                    "id":275,
                    "name":u"你的旋律",
                    "i":1
                },
                {
                    "id":276,
                    "name":u"酒吧",
                    "i":1
                },
                {
                    "id":149,
                    "name":u"日语",
                    "i":1
                },
                {
                    "id":168,
                    "name":u"法语",
                    "i":1
                },
                {
                    "id":122,
                    "name":u"70后",
                    "i":1
                },
                {
                    "id":123,
                    "name":u"80后",
                    "i":1
                },
                {
                    "id":124,
                    "name":u"90后",
                    "i":1
                },
                {
                    "id":174,
                    "name":u"钢琴",
                    "i":1
                },
                {
                    "id":175,
                    "name":u"木吉他",
                    "i":1
                },
                {
                    "id":176,
                    "name":u"小提琴",
                    "i":1
                },
                {
                    "id":181,
                    "name":u"萨克斯",
                    "i":1
                },
                {
                    "id":207,
                    "name":u"古筝",
                    "i":1
                },
                {
                    "id":225,
                    "name":u"笛子",
                    "i":1
                },
                {
                    "id":214,
                    "name":u"小清新",
                    "i":1
                },
                {
                    "id":208,
                    "name":u"唯美歌词",
                    "i":1
                },
                {
                    "id":210,
                    "name":u"成名曲",
                    "i":1
                },
                {
                    "id":209,
                    "name":u"劲爆车载",
                    "i":1
                },
                {
                    "id":200,
                    "name":u"情歌对唱",
                    "i":1
                },
                {
                    "id":219,
                    "name":u"清凉一夏",
                    "i":1
                },
                {
                    "id":202,
                    "name":u"怀旧华语",
                    "i":1
                },
                {
                    "id":203,
                    "name":u"怀旧粤语",
                    "i":1
                },
                {
                    "id":204,
                    "name":u"怀旧英语",
                    "i":1
                },
                {
                    "id":190,
                    "name":u"中国风",
                    "i":1
                },
                {
                    "id":192,
                    "name":u"旅行",
                    "i":1
                },
                {
                    "id":187,
                    "name":u"电影原声",
                    "i":1
                },
                {
                    "id":189,
                    "name":u"电视剧原声",
                    "i":1
                },
                {
                    "id":213,
                    "name":u"流行男声",
                    "i":1
                },
                {
                    "id":179,
                    "name":u"女声",
                    "i":1
                },
                {
                    "id":141,
                    "name":u"咖啡屋",
                    "i":1
                },
                {
                    "id":180,
                    "name":u"茗茶馆",
                    "i":1
                },
                {
                    "id":206,
                    "name":u"瑜伽",
                    "i":1
                },
                {
                    "id":127,
                    "name":u"经典",
                    "i":1
                },
                {
                    "id":148,
                    "name":u"唱作人",
                    "i":1
                },
                {
                    "id":167,
                    "name":u"网络流行",
                    "i":1
                },
                {
                    "id":144,
                    "name":u"动漫",
                    "i":1
                },
                {
                    "id":157,
                    "name":u"篮球",
                    "i":1
                },
                {
                    "id":160,
                    "name":u"早安",
                    "i":1
                },
                {
                    "id":161,
                    "name":u"晚安",
                    "i":1
                },
                {
                    "id":142,
                    "name":u"失眠",
                    "i":1
                },
                {
                    "id":166,
                    "name":u"儿歌",
                    "i":1
                },
                {
                    "id":146,
                    "name":u"胎教",
                    "i":1
                },
                {
                    "id":227,
                    "name":u"中国摇滚",
                    "i":1
                },
                {
                    "id":223,
                    "name":u"Hip-Hop",
                    "i":1
                },
                {
                    "id":195,
                    "name":u"舞曲",
                    "i":1
                },
                {
                    "id":185,
                    "name":u"说唱",
                    "i":1
                },
                {
                    "id":186,
                    "name":u"英伦",
                    "i":1
                },
                {
                    "id":215,
                    "name":u"DJ热碟",
                    "i":1
                },
                {
                    "id":183,
                    "name":u"蓝调",
                    "i":1
                },
                {
                    "id":184,
                    "name":u"Bossa Nova",
                    "i":1
                },
                {
                    "id":173,
                    "name":u"R&B",
                    "i":1
                },
                {
                    "id":130,
                    "name":u"流行摇滚",
                    "i":1
                },
                {
                    "id":132,
                    "name":u"爵士",
                    "i":1
                },
                {
                    "id":133,
                    "name":u"乡村",
                    "i":1
                },
                {
                    "id":129,
                    "name":u"轻音乐",
                    "i":1
                },
                {
                    "id":134,
                    "name":u"电子",
                    "i":1
                },
                {
                    "id":135,
                    "name":u"慢摇",
                    "i":1
                },
                {
                    "id":131,
                    "name":u"古典",
                    "i":1
                }
            ],
            "type2":[
                {
                    "id":4558,
                    "name":u"周杰伦",
                    "i":2
                },
                {
                    "id":224,
                    "name":u"张韶涵",
                    "i":2
                },
                {
                    "id":7221,
                    "name":u"许嵩",
                    "i":2
                },
                {
                    "id":13578,
                    "name":u"BY2",
                    "i":2
                },
                {
                    "id":143,
                    "name":u"陈奕迅",
                    "i":2
                },
                {
                    "id":44,
                    "name":u"梁静茹",
                    "i":2
                },
                {
                    "id":265,
                    "name":u"王力宏",
                    "i":2
                },
                {
                    "id":40089,
                    "name":u"EXO-M",
                    "i":2
                },
                {
                    "id":16257,
                    "name":u"Justin Bieber",
                    "i":2
                },
                {
                    "id":11606,
                    "name":u"林宥嘉",
                    "i":2
                },
                {
                    "id":21414,
                    "name":u"Bruno Mars",
                    "i":2
                },
                {
                    "id":6499,
                    "name":u"张杰",
                    "i":2
                },
                {
                    "id":109,
                    "name":u"孙燕姿",
                    "i":2
                },
                {
                    "id":6966,
                    "name":u"Rihanna",
                    "i":2
                },
                {
                    "id":4417,
                    "name":u"Avril Lavigne",
                    "i":2
                },
                {
                    "id":74,
                    "name":u"五月天",
                    "i":2
                },
                {
                    "id":4712,
                    "name":u"Michael Jackson",
                    "i":2
                },
                {
                    "id":163,
                    "name":u"刘德华",
                    "i":2
                },
                {
                    "id":4651,
                    "name":u"罗志祥",
                    "i":2
                },
                {
                    "id":11809,
                    "name":u"少女时代",
                    "i":2
                },
                {
                    "id":10,
                    "name":u"陈绮贞",
                    "i":2
                },
                {
                    "id":12578,
                    "name":u"Adele",
                    "i":2
                },
                {
                    "id":4740,
                    "name":u"黄小琥",
                    "i":2
                },
                {
                    "id":4286,
                    "name":u"林俊杰",
                    "i":2
                },
                {
                    "id":87,
                    "name":u"张国荣",
                    "i":2
                },
                {
                    "id":29,
                    "name":u"黄耀明",
                    "i":2
                },
                {
                    "id":11921,
                    "name":u"Taylor Swift",
                    "i":2
                },
                {
                    "id":24833,
                    "name":u"胡夏",
                    "i":2
                },
                {
                    "id":264,
                    "name":u"王菲",
                    "i":2
                },
                {
                    "id":112,
                    "name":u"蔡健雅",
                    "i":2
                },
                {
                    "id":13769,
                    "name":u"Lady GaGa",
                    "i":2
                },
                {
                    "id":141,
                    "name":u"张惠妹",
                    "i":2
                },
                {
                    "id":4404,
                    "name":u"WestLife",
                    "i":2
                },
                {
                    "id":6494,
                    "name":u"Whitney Houston",
                    "i":2
                },
                {
                    "id":5161,
                    "name":u"久石让",
                    "i":2
                },
                {
                    "id":5675,
                    "name":u"Super Junior",
                    "i":2
                },
                {
                    "id":4607,
                    "name":u"张靓颖",
                    "i":2
                },
                {
                    "id":218,
                    "name":u"S.H.E",
                    "i":2
                },
                {
                    "id":54,
                    "name":u"莫文蔚",
                    "i":2
                },
                {
                    "id":7080,
                    "name":u"The Cranberries",
                    "i":2
                },
                {
                    "id":4880,
                    "name":u"Eminem",
                    "i":2
                },
                {
                    "id":4660,
                    "name":u"Mariah Carey",
                    "i":2
                },
                {
                    "id":13203,
                    "name":u"萧敬腾",
                    "i":2
                },
                {
                    "id":118,
                    "name":u"容祖儿",
                    "i":2
                },
                {
                    "id":126,
                    "name":u"小野丽莎",
                    "i":2
                },
                {
                    "id":5470,
                    "name":u"白智英",
                    "i":2
                },
                {
                    "id":11424,
                    "name":u"AKB48",
                    "i":2
                },
                {
                    "id":4620,
                    "name":u"郑秀文",
                    "i":2
                },
                {
                    "id":101,
                    "name":u"陶喆",
                    "i":2
                },
                {
                    "id":113,
                    "name":u"Twins",
                    "i":2
                },
                {
                    "id":51,
                    "name":u"刘若英",
                    "i":2
                },
                {
                    "id":3347,
                    "name":u"古巨基",
                    "i":2
                },
                {
                    "id":146,
                    "name":u"谢霆锋",
                    "i":2
                },
                {
                    "id":171,
                    "name":u"杨千嬅",
                    "i":2
                },
                {
                    "id":5194,
                    "name":u"MC梦",
                    "i":2
                },
                {
                    "id":5437,
                    "name":u"岛谷瞳",
                    "i":2
                },
                {
                    "id":9426,
                    "name":u"X Japan",
                    "i":2
                },
                {
                    "id":2924,
                    "name":u"Jay-Z",
                    "i":2
                },
                {
                    "id":4615,
                    "name":u"李宇春",
                    "i":2
                },
                {
                    "id":174,
                    "name":u"张学友",
                    "i":2
                },
                {
                    "id":4365,
                    "name":u"周传雄",
                    "i":2
                },
                {
                    "id":159,
                    "name":u"胡彦斌",
                    "i":2
                },
                {
                    "id":4411,
                    "name":u"王筝",
                    "i":2
                },
                {
                    "id":11979,
                    "name":u"丁当",
                    "i":2
                },
                {
                    "id":5398,
                    "name":u"倖田來未",
                    "i":2
                },
                {
                    "id":30873,
                    "name":u"love solfege",
                    "i":2
                },
                {
                    "id":1496,
                    "name":u"Green Day",
                    "i":2
                },
                {
                    "id":5302,
                    "name":u"Muse",
                    "i":2
                },
                {
                    "id":230,
                    "name":u"迪克牛仔",
                    "i":2
                },
                {
                    "id":219,
                    "name":u"张敬轩",
                    "i":2
                },
                {
                    "id":4359,
                    "name":u"潘玮柏",
                    "i":2
                },
                {
                    "id":6028,
                    "name":u"A-Lin",
                    "i":2
                },
                {
                    "id":173,
                    "name":u"陈慧琳",
                    "i":2
                },
                {
                    "id":6130,
                    "name":u"凤飞飞",
                    "i":2
                },
                {
                    "id":4605,
                    "name":u"弦子",
                    "i":2
                },
                {
                    "id":5422,
                    "name":u"椎名林檎",
                    "i":2
                },
                {
                    "id":5087,
                    "name":u"宇多田光",
                    "i":2
                },
                {
                    "id":965,
                    "name":u"David Guetta",
                    "i":2
                },
                {
                    "id":89,
                    "name":u"张震岳",
                    "i":2
                },
                {
                    "id":6415,
                    "name":u"Evanescence",
                    "i":2
                },
                {
                    "id":6621,
                    "name":u"曹格",
                    "i":2
                },
                {
                    "id":4518,
                    "name":u"黑豹",
                    "i":2
                },
                {
                    "id":75,
                    "name":u"伍佰",
                    "i":2
                },
                {
                    "id":5941,
                    "name":u"小旺福",
                    "i":2
                },
                {
                    "id":5195,
                    "name":u"平井坚",
                    "i":2
                },
                {
                    "id":15370,
                    "name":u"沫小薰",
                    "i":2
                },
                {
                    "id":5705,
                    "name":u"岚",
                    "i":2
                },
                {
                    "id":11304,
                    "name":u"Guns N' Roses",
                    "i":2
                },
                {
                    "id":1066,
                    "name":u"方大同",
                    "i":2
                },
                {
                    "id":8440,
                    "name":u"Florence + the Machine",
                    "i":2
                },
                {
                    "id":11593,
                    "name":u"Enrique Iglesias",
                    "i":2
                },
                {
                    "id":4604,
                    "name":u"汪峰",
                    "i":2
                },
                {
                    "id":11626,
                    "name":u"郭静",
                    "i":2
                },
                {
                    "id":5558,
                    "name":u"张悬",
                    "i":2
                },
                {
                    "id":15961,
                    "name":u"2NE1",
                    "i":2
                },
                {
                    "id":5438,
                    "name":u"仓木麻衣",
                    "i":2
                },
                {
                    "id":14207,
                    "name":u"IU",
                    "i":2
                },
                {
                    "id":4946,
                    "name":u"The Eagles",
                    "i":2
                },
                {
                    "id":1577,
                    "name":u"杨幂",
                    "i":2
                },
                {
                    "id":4736,
                    "name":u"Akon",
                    "i":2
                },
                {
                    "id":4709,
                    "name":u"Céline Dion",
                    "i":2
                },
                {
                    "id":167,
                    "name":u"张信哲",
                    "i":2
                },
                {
                    "id":4351,
                    "name":u"范玮琪",
                    "i":2
                },
                {
                    "id":4367,
                    "name":u"王心凌",
                    "i":2
                },
                {
                    "id":5613,
                    "name":u"H.O.T",
                    "i":2
                },
                {
                    "id":13959,
                    "name":u"2PM",
                    "i":2
                },
                {
                    "id":165,
                    "name":u"萧亚轩",
                    "i":2
                },
                {
                    "id":5684,
                    "name":u"w-inds.",
                    "i":2
                },
                {
                    "id":12492,
                    "name":u"王若琳",
                    "i":2
                },
                {
                    "id":290,
                    "name":u"Coldplay",
                    "i":2
                },
                {
                    "id":4681,
                    "name":u"James Blunt",
                    "i":2
                },
                {
                    "id":4718,
                    "name":u"P!nk",
                    "i":2
                },
                {
                    "id":178,
                    "name":u"吴克羣",
                    "i":2
                },
                {
                    "id":4658,
                    "name":u"杨丞琳",
                    "i":2
                },
                {
                    "id":4422,
                    "name":u"牛奶咖啡",
                    "i":2
                },
                {
                    "id":4983,
                    "name":u"Maroon 5",
                    "i":2
                },
                {
                    "id":12855,
                    "name":u"Lady Antebellum",
                    "i":2
                },
                {
                    "id":13841,
                    "name":u"SHINee",
                    "i":2
                },
                {
                    "id":5595,
                    "name":u"小事乐团",
                    "i":2
                },
                {
                    "id":4762,
                    "name":u"Usher",
                    "i":2
                },
                {
                    "id":13948,
                    "name":u"G.E.M. 邓紫棋",
                    "i":2
                },
                {
                    "id":4586,
                    "name":u"Black Eyed Peas",
                    "i":2
                },
                {
                    "id":227,
                    "name":u"蔡依林",
                    "i":2
                },
                {
                    "id":2923,
                    "name":u"Linkin Park",
                    "i":2
                },
                {
                    "id":4708,
                    "name":u"Britney Spears",
                    "i":2
                },
                {
                    "id":4716,
                    "name":u"Madonna",
                    "i":2
                },
                {
                    "id":8394,
                    "name":u"卢广仲",
                    "i":2
                },
                {
                    "id":4161,
                    "name":u"Beyoncé",
                    "i":2
                },
                {
                    "id":11760,
                    "name":u"Sara Bareilles",
                    "i":2
                },
                {
                    "id":11733,
                    "name":u"BigBang",
                    "i":2
                },
                {
                    "id":4800,
                    "name":u"滨崎步",
                    "i":2
                },
                {
                    "id":4915,
                    "name":u"东方神起",
                    "i":2
                },
                {
                    "id":5484,
                    "name":u"蔡妍",
                    "i":2
                },
                {
                    "id":4435,
                    "name":u"BoA",
                    "i":2
                },
                {
                    "id":4706,
                    "name":u"Rain",
                    "i":2
                },
                {
                    "id":5829,
                    "name":u"凤凰传奇",
                    "i":2
                },
                {
                    "id":13157,
                    "name":u"Katy Perry",
                    "i":2
                },
                {
                    "id":6033,
                    "name":u"吴雨霏",
                    "i":2
                },
                {
                    "id":11761,
                    "name":u"筷子兄弟",
                    "i":2
                },
                {
                    "id":5924,
                    "name":u"苏打绿",
                    "i":2
                },
                {
                    "id":1059,
                    "name":u"何晟铭",
                    "i":2
                },
                {
                    "id":2,
                    "name":u"BEYOND",
                    "i":2
                },
                {
                    "id":5371,
                    "name":u"SARA（韩国）",
                    "i":2
                },
                {
                    "id":7298,
                    "name":u"陈瑞",
                    "i":2
                },
                {
                    "id":4713,
                    "name":u"邓丽君",
                    "i":2
                },
                {
                    "id":4427,
                    "name":u"信乐团",
                    "i":2
                },
                {
                    "id":139,
                    "name":u"王杰",
                    "i":2
                },
                {
                    "id":62,
                    "name":u"任贤齐",
                    "i":2
                }
            ],
            "type3":[
                {
                    "id":259,
                    "name":u"回忆",
                    "i":3
                },
                {
                    "id":136,
                    "name":u"伤感",
                    "i":3
                },
                {
                    "id":137,
                    "name":u"寂寞",
                    "i":3
                },
                {
                    "id":138,
                    "name":u"甜蜜",
                    "i":3
                },
                {
                    "id":140,
                    "name":u"快乐",
                    "i":3
                },
                {
                    "id":139,
                    "name":u"励志",
                    "i":3
                },
                {
                    "id":194,
                    "name":u"激情",
                    "i":3
                },
                {
                    "id":211,
                    "name":u"安静",
                    "i":3
                },
                {
                    "id":212,
                    "name":u"想哭",
                    "i":3
                },
                {
                    "id":217,
                    "name":u"疗伤",
                    "i":3
                },
                {
                    "id":224,
                    "name":u"思念",
                    "i":3
                }
            ]
        }
